### ISSUE TITLE
When I train first model, It does not create mappings.pkl

### ISSUE THREAD

**Issue by changukshin** [onurgu/ner-tagger-dynet#3]
in model_tensorflow.save_mappings

if overwrite_mappings is off(0) and the mapping file does not exists,
It does not create new one.

So the flow must be like

```python
if not exists(mapping_file):
    create_one()
else:
    if overwrite_option:
        create_one()
    else:
        #handle_unexpected_behaviour
        #or dismiss?
```

**Comment by onurgu** [comment]
Thank you for your attention.

I believe it's fixed with the commit above.
