### ISSUE TITLE
creation of eval log folder

### ISSUE THREAD

**Issue by mgoksu** [onurgu/ner-tagger-dynet#6]
./evaluation/temp/eval_logs is not created automatically which stops the training
with an error message something similar to below during evaluation:
IOError: [Errno 2] No such file or directory: './evaluation/temp/eval_logs/dev.eval.1212048.epoch-0000.output'

**Comment by onurgu** [comment]
It was already fixed in a different branch however it was not merged into the master branch.

It is now fixed with 576ec8e1c3a8bfe6f825dadf49db8f046823dc97 in the master branch also.
